"""empty message

Revision ID: f6b48c67593c
Revises: 4e0e6485e4ee
Create Date: 2024-07-18 14:59:50.867843

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'f6b48c67593c'
down_revision: Union[str, None] = '4e0e6485e4ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
